apiVersion: batch/v1 
kind: Job 
metadata:   
  generateName: kube-job-
  labels:     
    jobgroup: jobexample 
spec:   
  template:     
    metadata:       
      name: kubejob       
      labels:         
        jobgroup: jobexample     
    spec:       
      containers:       
      - name: c         
        image: mt2h/kubernetes-job-demo:latest         
        args: ["10"]       
      restartPolicy: OnFailure
