apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - name: memory-demo-crt
      image: polinux/stress
      resources:
        limits:
          #memory: "200Mi"
          memory: "1000Gi"
        requests:
          #memory: "100Mi"
          memory: "1000Gi"
      command: ["stress"]
      #args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
