apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
    - name: cpu-demo-crt
      image: vish/stress
      resources:
        limits:
          #cpu : "1000m" #"1"
          cpu : "100"
        requests:
          #cpu: "500m" #"0.5"
          cpu: "100"
      args:
        - -cpus
        - "2"
