apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: myuser
  password: mypassoword
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: myvolume
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: myvolume
    secret:
      secretName: mysecret
      items:
      - key: username
        path: user.txt
      - key: password
        path: mypassoword.txt
